services:
  - type: web
    name: readwick-api
    runtime: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: APP_JWT_SECRET
        generateValue: true
      - key: APP_CORS_ORIGINS
        sync: false
      - key: JAVA_TOOL_OPTIONS
        value: -Xmx384m
    healthCheckPath: /api/auth/session
